<%@ Page Title="" Language="C#" MasterPageFile="~/Admin.master" AutoEventWireup="true" CodeFile="Banners.aspx.cs" Inherits="Admin_Banners" %>

<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent2" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent2" Runat="Server">
<h3>Banners
    </h3>
        <asp:Button ID="Button2" runat="server" CssClass="button" Text="Ny annons" 
            UseSubmitBehavior="False" PostBackUrl="~/Admin/AddBanner.aspx" onclick="Button2_Click" />
        <asp:GridView ID="GridView1" runat="server" AllowPaging="True" 
            AllowSorting="True" AutoGenerateColumns="False" DataKeyNames="id" 
            DataSourceID="SqlDataSource1" AutoGenerateDeleteButton="True" 
         
            CellPadding="4" 
            ForeColor="#333333" GridLines="None">
            <RowStyle BackColor="#EFF3FB" />
            <Columns>
               
             
                <asp:BoundField DataField="NavigateUrl" HeaderText="Länk" 
                    SortExpression="NavigateUrl" />
               
                <asp:BoundField DataField="startDate" HeaderText="Startdatum" 
                    SortExpression="startDate" />
                <asp:BoundField DataField="endDate" HeaderText="Slutdatum" 
                    SortExpression="endDate" />
               
                     <asp:CommandField ShowSelectButton="False"  />
               
            </Columns>
            <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
            <EmptyDataTemplate>
                &nbsp;
            </EmptyDataTemplate> 
            <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
            <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
            <EditRowStyle BackColor="#2461BF" />
            <AlternatingRowStyle BackColor="White" />
        </asp:GridView>

        <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
            DeleteCommand="DELETE FROM ads WHERE id= @id" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" 
            SelectCommand="SELECT * FROM [ads]"></asp:SqlDataSource>
        <br />
     
</asp:Content>

